#!/usr/bin/env sh

# Copyright 2015-2020 yanglb.com
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# For more information about the cg.jar, please vist the following page:
# https://github.com/excel-code-generator/code-generator
CG_PATH=/usr/local/lib/cg/bin/cg.jar
case "`uname`" in MINGW*)
  CG_PATH=$0.jar
esac

# update
do_update () {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/excel-code-generator/code-generator/master/install.sh)"
}

if [ "update" = "$1" ];then
  echo update code generator
  do_update
  exit 0
fi

if [ ! -f $CG_PATH ];then
  echo "`tput setaf 1`ERROR: The file \"$CG_PATH\" does not exist.`tput sgr0`"
  echo "run \``tput setaf 2`cg update`tput sgr0`\` command to reinstall."
  echo
  echo "For more information about the cg.jar, please vist the following page:"
  echo "`tput setaf 4`https://github.com/excel-code-generator/code-generator `tput sgr0`"
  exit 1
fi

java -jar $CG_PATH $@
