/**
 * Copyright 2015 yanglb.com
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.yanglb.utilitys.codegen.core.translator.impl;

import java.util.Map;

import com.yanglb.utilitys.codegen.core.model.TableModel;
import com.yanglb.utilitys.codegen.core.translator.BaseMsgTranslator;
import com.yanglb.utilitys.codegen.exceptions.CodeGenException;
import com.yanglb.utilitys.codegen.utility.StringUtility;

public class MsgCSTranslatorImpl extends BaseMsgTranslator {
	protected String msgLang = "";

	@Override
	protected void onBeforeTranslate() throws CodeGenException {
		super.onBeforeTranslate();
		
		// 当前生成的国际化语言
		this.msgLang = this.settingMap.get("MsgLang");
		
		// 文件名
		String fileName = getFileName();
		if (fileName.equals("")) {
			// 空文件名
			fileName = this.msgLang;
		} else {
			if(!this.msgLang.equals("default")) {
				fileName = fileName + "." + this.msgLang;
			}
		}
		
		this.writableModel.setFileName(fileName);
		this.writableModel.setExtension("resx");
		this.writableModel.setFilePath("");
	}

	@Override
	protected void onTranslate() throws CodeGenException {
		super.onTranslate();
		StringBuilder sb = this.writableModel.getData();
		sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n" + 
//				this.genHeader() +
				this.settingMap.get("head") +
				"<root>\r\n");
		
		for(TableModel tblModel : this.model) {
			// 添加Sheet注释
			sb.append(String.format("    \r\n"));
			sb.append(String.format("    <!-- %s -->\r\n", tblModel.getSheetName()));
			
			for(Map<String, String> itm : tblModel.toList()) {
				String id = itm.get("id");
				if(StringUtility.isNullOrEmpty(id)) continue;
				
				// 对字符串进行转换
				String value = this.convert2CSCode(itm.get(this.msgLang));
				sb.append(String.format("    <data name=\"%s\">\r\n", id));
				sb.append(String.format("        <value>%s</value>\r\n", value));
				sb.append(String.format("    </data>\r\n"));
			}
		}
		
		int idx = sb.lastIndexOf(",");
		if(idx != -1) {
			sb.deleteCharAt(idx);
		}
		sb.append("</root>\r\n");
	}
	
	private String genHeader() {
		StringBuilder sb = new StringBuilder();
		sb.append(String.format("<!--\r\n"));
		sb.append(String.format("    %s\r\n", this.settingMap.get("generatorCopyright")));
		sb.append(String.format("    Auto generated by %s v%s\r\n", this.settingMap.get("generatorName"), this.settingMap.get("generatorVersion")));
		sb.append(String.format("    %s\r\n", this.model.get(0).getGenerationDate()));
//		sb.append(String.format("    {generationDate}\r\n"));
		sb.append(String.format("    %s\r\n", this.settingMap.get("generatorRepository")));
		sb.append(String.format("-->\r\n"));
		return sb.toString();
	}
	
	private String convert2CSCode(String value) {
		if(value == null) return null;
		
		// 先替换\r\n，防止有文档只有\r或\n 后面再替换一次
		value = value.replaceAll("\r\n", "\\\\r\\\\n");
		value = value.replaceAll("\r", "\\\\r\\\\n");
		value = value.replaceAll("\n", "\\\\r\\\\n");
		return value;
	}

//	@Override
//	protected void onAfterTranslate() throws CodeGenException {
////		super.onAfterTranslate();
//		// 不需要替换标记
//	}
}
